[theme]
primaryColor = '#94610B'
backgroundColor = '#0E1117'
secondaryBackgroundColor = '#262730'
textColor = '#FAFAFA'

[server]
headless = false
runOnSave = true

[client]
showSidebarNavigation = true